version: "3.9"

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    restart: always
    networks:
      - vulnlab

  webgoat:
    image: webgoat/webgoat
    container_name: webgoat
    restart: always
    networks:
      - vulnlab

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    restart: always
    networks:
      - vulnlab

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    restart: always
    depends_on:
      - juice-shop
      - webgoat
      - dvwa
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vulnlab

networks:
  vulnlab:
    driver: bridge
